### ISSUE TITLE
Silently Fails (dbt 1.4 with Synapse)

### ISSUE THREAD

**Issue by alittlesliceoftom** [montara-io/dbt-command-center#17]
On dbt 1.4 with dbt synapse adapter the dashboard shows little output. 

![image](https://github.com/montara-io/dbt-command-center/assets/11210917/d4d8cf64-f126-45a1-b58f-b9d6328e123d)

Logs show 200s for output.json, but 404s for other files: 
![image](https://github.com/montara-io/dbt-command-center/assets/11210917/844e436c-491d-4fd3-8f44-099829ef12ad)

Python 3.11.3
```
(dbtenv) λ pip list | grep dbt
dbt-command-center        0.1.17
dbt-core                  1.4.9
dbt-extractor             0.4.1
dbt-sqlserver             1.4.3
dbt-synapse               1.4.0
```

**Comment by atardadi** [comment]
Hey @alittlesliceoftom can you make sure `dbt parse` is passing?
We have a open issue to support non-compiling projects with a meaningful message

**Comment by alittlesliceoftom** [comment]
Yeh I'll have to re-install, but will try

**Comment by alittlesliceoftom** [comment]
Hmmm.. I re-installed, ran dbt parse then triggered and it's now running ok (except pipeline view). 

Which is consistent with logs. 

![image](https://github.com/montara-io/dbt-command-center/assets/11210917/88cfb7d2-0bb6-47b9-b2d3-814d04695059)

**Comment by atardadi** [comment]
That's odd.. We initially run dbt parse to get the dbt artifacts, which graph_summary.json should be one of them.

Are you able to find it in the Montara_target folder?

**Comment by alittlesliceoftom** [comment]
I think probably issue is that we're running an older version of dbt...
I'll try again after an upgrade, but would recommend requiring a certain
version in your setup.py perhaps?

*Tom O'Neill*

**Comment by atardadi** [comment]
@alittlesliceoftom it should work now. 
Try reinstalling 
`pip install --force-reinstall dbt_command_center`

**Comment by alittlesliceoftom** [comment]
Hey belatedly confirming this is fixed for me, thanks so much.

**Comment by atardadi** [comment]
@alittlesliceoftom I think so
